version: '3'

services:
  db:
    image: 'amazon/dynamodb-local'

  api:
    build:
      context: ..
    
    env_file: ../.env

    volumes:
      - ..:/app

    ports:
      - 8080:8080

    command: go run cmd/api.go